### ISSUE TITLE
--nested-ca seems to be broken (create_one_root_3_intca.sh fails)

### ISSUE THREAD

**Issue by joaocc** [egberts/tls-ca-manage#3]
It seems that creating any AmeComponent child fails (cannot locate parent folder)

**Comment by joaocc** [comment]
It seems the commit saying this wold not fix, was detected by github as saying it fixed :) reopening.

**Comment by egberts** [comment]
NO!  I did not indicate anything closely resembling 'would not fix'; I'm hoping that this is a bot or something;  am looking at this now.

**Comment by joaocc** [comment]
Sure! I meant "my comment" saying that the "proposed original commit would not fix the issue despite the fact that I thought it would" is what got picked up by github :) All good!
