### ISSUE TITLE
Add support for specifying cipher passwords via files

### ISSUE THREAD

**Issue by joaocc** [egberts/tls-ca-manage#4]
I have made some changes but not sure if consistent with the style. Will try to push soon.

**Comment by joaocc** [comment]
Added in #[c9da6e9](https://github.com/egberts/tls-ca-manage/pull/2/commits/c9da6e9b599c1706a4bc14f416424df1a32bec4d)

**Comment by egberts** [comment]
Thanks again for your wonderful input.

I like this as a way for a continual supporting of the batch mode
