### ISSUE TITLE
OpenSSL option -no-CAstore only seems to be supported on OpenSSL 3.0

### ISSUE THREAD

**Issue by joaocc** [egberts/tls-ca-manage#5]
Prob would be good to add mention to supported OpenSSL version

**Comment by egberts** [comment]
openSSL v1.1.1k March 25, 2021

**Comment by egberts** [comment]
https://github.com/egberts/tls-ca-manage/commit/8c0229d6f77b616798bc11beec6e002b70efc67e

**Comment by joaocc** [comment]
Hi. Thanks. However, it seems that -no-CAstore is only recognized in OpenSSL3.
Btw, I installed openssl3 (and linked openssl to it) and everything seems to be working (CA generation, and maybe verification). Didn't rest cert yet (had some issues but no time yet).
Thanks
