### ISSUE TITLE
exported cert chains do not appear to include all levels

### ISSUE THREAD

**Issue by joaocc** [egberts/tls-ca-manage#7]
Trying to replicate the example in https://github.com/egberts/tls-ca-manage/blob/master/examples/create_one_root_3_intca.sh, I added a codesign CA as child of AcmeIdentity.
The chained cert for codesign only includes the direct parent (AcmeIdentity) and not the other ancestors (AcmeNetwork) and root (AcmeRoot)

**Comment by egberts** [comment]
Wow....  Need to navigate the chain, reconstruct a list of PEMs for a proper chained PEM file, I concur.

**Comment by egberts** [comment]
i think i may have goofed.  then again, i may have not.

there is a magical text file called `PARENT_CA` that contains a relative directory path to the parent CA of its node.  

it is one of those times where you simply were unsure of bash programming capability to navigate a tree quickly so this file was a forethought in search of an application: now, there it is.

This should be a quick fix soon.

**Comment by egberts** [comment]
There ye go.  Chains are found by default in /etc/ssl/ca along with their corresponding .crt, and .crl.

Now at the HEAD.

https://github.com/egberts/tls-ca-manage/commit/b3e31d7e0889715098d0731276788eef6aaed201
